stages:
  preprocess:
    cmd: python services/preprocessing/preprocessing.py
    deps:
      - data/raw
      - services/preprocessing/preprocessing.py
    outs:
      - data/processed
      - data/patients

  patient_data_pull:
    cmd: python services/patient_data_pull/patient_data_pull.py
    deps:
      - services/patient_data_pull/patient_data_pull.py
      - data/patients
    outs:
      - data/patients_inference

  train:
    cmd: >
      python services/model_training/train.py
      --data_path data/processed
      --model_path models/epilepsy_model.keras
      --metrics_path metrics/model_metrics.json
      --epochs 10
      --batch_size 15
    deps:
      - data/processed
      - services/model_training/train.py
    outs:
      - models
      - metrics

  evaluate:
    cmd: python services/evaluate/evaluate.py
    deps:
      - services/evaluate/evaluate.py
      - models
      - metrics
    outs:
      - production


